### ISSUE TITLE
Research the article and then the page becomes blank

### ISSUE THREAD

**Issue by siyuan-zhang** [RoiArthurB/Side-Auto_Sci-Hub#1]
When i open a article website, and then click the auto-sci-hub. The page will becomes a blank  and Can't open the article pdf page

**Comment by RoiArthurB** [comment]
Hello,

Could you send me the link you used and which browser do you use please? :)

**Comment by siyuan-zhang** [comment]
Thanks for your replay.  At afternoon,  it can work again. It sound likes that the sci-hub database itself is out of order and  recovers this afternoon.

**Comment by RoiArthurB** [comment]
Ok, so I'll close the issue assuming that the problem is solved (and was not depending on my plugin) ^^
