### ISSUE TITLE
Put new tab next to current tab

### ISSUE THREAD

**Issue by Clef-0** [RoiArthurB/Side-Auto_Sci-Hub#10]
I sometimes use this extension while I have a lot of tabs open, but (in Firefox at least), the new tab opened by clicking the extension icon appears at the end of my tab list instead of after my current tab. Putting the Sci-Hub tab directly after the tab that spawned it would keep relevant tabs next to each other and would be more consistent with Firefox's Open Link in New Tab.

**Comment by RoiArthurB** [comment]
Hi ! 
I'll do my best on it, I can't give you any deadline (it will be Christmas, so I can't promise anything at all) but it's in my backlog for sure ^^

**Comment by RoiArthurB** [comment]
I have some trouble updating the version on Firefox (I think my account has been soft-lock because I'm badly requesting Firefox Server with my Github Action), but I'll do the update as soon as possible (the code is working ;) )
