### ISSUE TITLE
New Tab Url Incorrect

### ISSUE THREAD

**Issue by sj365** [RoiArthurB/Side-Auto_Sci-Hub#11]
Auto SciHub on Firefox 71 Windows 10

on this site https://science.sciencemag.org/content/366/6464/447 if you click AutoSciHub icon in Firefox it will attempt to open in a new tab

https://sci-hub.se//ttps%3A%2F%2Fscience.sciencemag.org%2Fcontent%2F366%2F6464%2F447

This url is incorrect since it is missing the h in https and the page will not open.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RoiArthurB** [comment]
Hi, thanks for your issue !

This is a kind of known issue and comes from WhereIsSciHub. I did [a PR](https://gitlab.com/Flockademic/whereisscihub/merge_requests/4) to fix it but I'm still waiting... 

Also this issue is related to this one : https://github.com/RoiArthurB/Side-Auto_Sci-Hub/issues/5
