### ISSUE TITLE
Wrong URL 

### ISSUE THREAD

**Issue by AS30-spec** [RoiArthurB/Side-Auto_Sci-Hub#13]
**Describe the bug**
Hello,
I just would like to report a bug occuring in my case.
When i click on the addons, the new tab opens well, but it does not work because it is missing a "h" to the URL:
For example:
"https://186.2.163.90//ttps%3A%2F%2Fwww.sci etc.."

I do not know if this is normal? What should I do to solve this problem?

![image](https://user-images.githubusercontent.com/60074038/72686661-5ecc4580-3af7-11ea-9874-8cbae5e7263f.png)

Thank you a lot for this great addons! and in advance for your reply

**Comment by RoiArthurB** [comment]
The problem is a known issue (cf https://github.com/RoiArthurB/Side-Auto_Sci-Hub/issues/12 ), but the IP address is surprising...

**Comment by AS30-spec** [comment]
Thank you for your reply, I did not see the issue #12. For the IP, I am in a country which blocked the SciHub addresses. I am using anoter addon to Bypass sci-hub DNS censorship. I guess this could be the reason why the IP address is surprising.

I will try to fix my bug. Again thank you for your reply!

**Comment by RoiArthurB** [comment]
Ok for the IP address :)

Soo the bug about the missing "h" is something from my plugin I'm working on. I'll close your issue because it's a duplicate o/
