### ISSUE TITLE
Firefox Android, Sci-Hub opens in a non-Private tab while in Private Browsing

### ISSUE THREAD

**Issue by Clef-0** [RoiArthurB/Side-Auto_Sci-Hub#14]
**Describe the bug**
When pressing Open in Sci-Hub while in a Private Browsing tab on Android, it opens in a non-Private tab.

**To Reproduce**
1. Load a journal article page in Private Browsing on Firefox Android
2. Open menu and click Open in Sci-Hub

**Expected behavior**
Sci-Hub opening in a Private Tab next to the current one.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android
 - Browser: Firefox
 - Version: 68.4.2

**Comment by RoiArthurB** [comment]
Hi,
I really have no idea about how to fix that issue... So unless you can help, I'm afraid I won't be able to fix it :/

**Comment by Jackymancs4** [comment]
> I really have no idea about how to fix that issue

pretty much you can't. For references:
https://bugzilla.mozilla.org/show_bug.cgi?id=1372178

As always users can vote the issue, and tell why it's important.
Also might be related/of interest:

https://bugzilla.mozilla.org/show_bug.cgi?id=1404014
https://bugzilla.mozilla.org/show_bug.cgi?id=1493426

**Comment by RoiArthurB** [comment]
@Jackymancs4 I haven't digged it yet, but it seems that I can open a new tab (instead of new window) in private mode which is what @Clef-0 is looking for ^^

I'll take an eye on it and keep you update here :bear:

**Comment by Jackymancs4** [comment]
> it seems that I can open a new tab

While I hope so, the title of https://bugzilla.mozilla.org/show_bug.cgi?id=1372178 says 

> WebExtension cannot open private browsing **tabs** or "windows" on Android

and the reasoning why is that is unfortunately pretty sound.

[browser.windows](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows) is not available on Android and [browser.tabs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) cannot create an incognito tabs

Still, I hope you'll find a way 👍🏻
