### ISSUE TITLE
[DISCUSSION] Integrate WISH link autodiscovery code in the extension

### ISSUE THREAD

**Issue by Jackymancs4** [RoiArthurB/Side-Auto_Sci-Hub#15]
Hello @RoiArthurB 
I've been following the recent updates and discussions.

I was wondering if you can consider to do (or accept a PR that does) what the title says.

Technically speaking, including and adapting this

```js
async function getUrls() {
  const sciHubId = 'Q21980377';
  const officialWebsiteProperty = 'P856';
  const sparql = `
    SELECT ?urls WHERE {
      { wd:${sciHubId} p:${officialWebsiteProperty} [wikibase:rank wikibase:PreferredRank; ps:${officialWebsiteProperty} ?urls]. }
    }
    `;
  const response = await fetch(`https://query.wikidata.org/sparql?format=json&query=${encodeURIComponent(sparql)}`);
  const data = await response.json();

  const urls = data.results.bindings.map(result => result.urls.value);

  return urls.sort(compareUrls);
}

function compareUrls(url1, url2) {
  // URL beginning with `https://`, and ending in a non-digit character (of the TLD) and a potential trailing slash
  const httpsDomainRE = /^https:\/\/(.*)\D\/?$/;
  // URL beginning with `http://`, and ending in a non-digit character (of the TLD) and a potential trailing slash
  const httpDomainRE = /^http:\/\/(.*)\D\/?$/;

  // Regular URL's pointing to an HTTPS address come first
  if (httpsDomainRE.test(url1)) {
    return -1;
  } else if(httpsDomainRE.test(url2)) {
    return 1;
  // IP addresses using HTTPS come second
  } else if(url1.substr(0, 5) === 'https') {
    return -1;
  } else if(url2.substr(0, 5) === 'https') {
    return 1;
  // Only then come regular domains hosted through naked HTTP
  } else if(httpDomainRE.test(url1)) {
    return -1;
  } else if(httpDomainRE.test(url2)) {
    return 1;
  }
  // And if both are an IP address through naked HTTP, we don't care which comes first:
  return 0;
}

```

taken from https://gitlab.com/Flockademic/whereisscihub/blob/master/index.js

From what I understand from [here](https://github.com/RoiArthurB/Side-Auto_Sci-Hub/issues/12#issuecomment-579669337) you already considered it. 

> The problem is that if I explicitly gather SH URLs in the plugin I'm afraid to not respect the Firefox's rules and having my plugin being struck :/

I think this is not a real problem, mainly because from a functional standpoint, what you would already do is redirect to sci-hub, just with a middle step.

Also, on the market there are other Sci Hub related extensions (namely https://addons.mozilla.org/firefox/addon/open-on-sci-hub) that literally hard-code the URLs and have been around for quite some time.

Right now, you are quite reliant on the maintenance of whereisscihub (even when the option-thing will be released, which is a great idea, someone will have to keep the code working and consistent the actual behaviour).

This idea should give you quite some independence, and relieve you from the burden of also maintaining server-side whereisscihub forks (which you are doing now).

**Comment by RoiArthurB** [comment]
Hi ! :bear: 

> I think this is not a real problem, mainly because from a functional standpoint, what you would already do is redirect to sci-hub, just with a middle step.

You've right, but I really appreciate this plugin to stay as light as possible and following the KISS principle. So I prefer having different simple elements (a light/KISS plugin, a light/KISS website, ...) doing different simple things (opening a new tab with a custom URL, scrapping and redirecting URL, ...).

> Also, on the market there are other Sci Hub related extensions (namely https://addons.mozilla.org/firefox/addon/open-on-sci-hub) that literally hard-code the URLs and have been around for quite some time.

Maybe it's mainly because the plugin is not popular enough and pass below Firefox reviewer's scan ? 🤷 I'll try to ask a Mozilla moderator their POV about SciHub and plugins about it to be sure

> This idea should give you quite some independence, and relieve you from the burden of also maintaining server-side whereisscihub forks (which you are doing now).

The main problem with this scrapping solution is that it'll be soon outdated : [Wikimedia projects blacklisted Sci-Hub URLs](https://gitlab.com/Flockademic/whereisscihub/issues/9)

> From what I understand from here you already considered it.

I think that with the option, people may be able to fix the WISH problem (if not maintain anymore, broken because of Wikimedia, blocked redirect because of FAI as in France, etc) with individual solution.

**Comment by Jackymancs4** [comment]
> following the KISS principle.

I was sure you would have said that xD

As a side note, I think you're mistaking the KISS principle (which says to keep the code simple and not overthink solutions but also do not refrain from adding needed/useful feature or logic) with the Unix Philosophy, which is something like "many products with one feature each".

> Maybe it's mainly because the plugin is not popular enough and pass below Firefox reviewer's scan ? 🤷

Maybe indeed

> I'll try to ask a Mozilla moderator their POV about SciHub and plugins about it to be sure

👍🏻

> The main problem with this scrapping solution is that it'll be soon outdated

That's my point, right now you are relying on someone else to fix WISH every time a method gets outdated, and in the mean time have to keep up your temporary fork with eventual fixes.

Moving the thing "in house" allows you (or contributors) to readily fix the extension on demand.

---

Obviously, all of this is just my opinion as a user :)

**Comment by RoiArthurB** [comment]
> As a side note, I think you're mistaking the KISS principle [...] with the Unix Philosophy ...

_Go learning the difference and will soon be back to agree with you_ 🤓

> Moving the thing "in house" allows you (or contributors) to readily fix the extension on demand.

But the problem remain mostly the same : I (or mainly me) will have to maintain that middleware 🤷
