### ISSUE TITLE
Cannot change the base URL

### ISSUE THREAD

**Issue by Deleetdk** [RoiArthurB/Side-Auto_Sci-Hub#17]
**Describe the bug**
I cannot change the base URL. Denmark has recently started blocking the Swedish and the Taiwan domains (.se, .tw), but the .shop one works. So I want to use that.

**To Reproduce**
1. Go to extension preferences
2. Click on enter any url (e.g. `http://sci-hub.shop/`)
3. Click save
4. Nothing happens, it keeps using the old one which results in waiting forever sense .se domain is blocked

**Expected behavior**
I expect it to use the new base URL

**Screenshots**
![Screenshot from 2020-01-30 15-30-36](https://user-images.githubusercontent.com/6759913/73458392-7caa6d80-4375-11ea-96b9-a25a754c6707.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Firefox
 - Version 71.0 (64-bit)

**Comment by RoiArthurB** [comment]
Hi !
Sorry, this option is a work in progress for now... It should be working in the next 2.0 :bear:

**Comment by RoiArthurB** [comment]
Fixed on the last release 2.0 🐻🐻

Enjoy :D
