### ISSUE TITLE
"Oops! We can’t find that page": extension removed from Firefox site

### ISSUE THREAD

**Issue by Deleetdk** [RoiArthurB/Side-Auto_Sci-Hub#18]
**Describe the bug**
Link to https://addons.mozilla.org/en-US/firefox/addon/auto-sci-hub/ is broken

**To Reproduce**
Click link

**Expected behavior**
I want a way to download the extension

**Screenshots**
![Screenshot from 2020-03-24 22-00-10](https://user-images.githubusercontent.com/6759913/77476415-d762c180-6e1a-11ea-80af-30b6e5dc8d0a.png)

**Comment by RoiArthurB** [comment]
I know, I received a mail from Firefox saying that they had to remove the plugin because it was 

Here's the mail : 
> Dear contributor,  
>
> We received a notification under Mozilla’s Digital Millennium Copyright Act (“DMCA”) and Trademark policy (https://www.mozilla.org/about/legal/report-infringement/) complaining of allegedly infringing activity by you on our service at https://addons.mozilla.org/en-US/firefox/addon/auto-sci-hub. We have removed or disabled access to your add-on identified by the claimant as infringing the claimant's trademark.
>
> The notice included the following report:
>
> From DeVore & DeMarco LLP:
>
> We are litigation counsel for Elsevier Inc., a leading publisher of scientific, engineering, and medical books and journals. Elsevier provides , among other things, the ScienceDirect platform, through which it distributes scientific journal articles in which it holds the copyright. In order to protect its copyright interest in those articles, Elsevier brought a civil action against a number of websites commonly known as "Sci-Hub" and "LibGen" or "Library Genesis" and their respective mirrors which engage in the large-scale infringement of those copyrights. On June 21, 2017, Elsevier obtained a judgement against those websites which, among other things, enjoined the websites, their operators, and anyone acting in concert with them, from infringing Elsevier' s copyrighted works or assisting others in doing so.
>
> We write to inform you of the presence of a number of add-ons for the Firefox web browser which are designed specifically to assist their users in infringing Elsevier 's (and other publisher') copyrights through the websites operated by the defendants in the above-mentioned civil action. We request that these extensions be removed from the Firefox Browser Add-Ons website (addons.mozilla.org) because they (1) violate the DMCA, including Section 1201 (circumvention of copyright protection systems); (2) operate in concert with the defendants in the above-mentioned civil action to violate Elsevier's copyrights in violation of the court 's order enjoining such conduct; and (3) are manifestly in violation of Mozilla's Conditions of Use (https://www.mozilla.om:/enUS/about/legal /acceptable-useD which expressly prohibit, among other things, illegal content and content which violates the copyright or other intellectual property rights of others. We therefore request that the following add-ons be promptly removed.
