### ISSUE TITLE
Other way to publish/auto-update plugin ?

### ISSUE THREAD

**Issue by RoiArthurB** [RoiArthurB/Side-Auto_Sci-Hub#22]
From @Clef-0
> As an aside, for Firefox users, it looks like [you can submit addons to AMO to be signed without listing them on AMO](https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ) (see 'How do I get my add-ons signed if they are not hosted on addons.mozilla.org (AMO)?'), which would let you auto-update the addon outside of AMO and let users install it non-temporarily, and it appears to be an automated review process that they claim won't be used for copyright enforcement. I don't use AMO, so I don't know the details, but their instructions sound pretty straight forward and it would be make the addon convenient for Firefox users again.

**Comment by Clef-0** [comment]
I just tested this (I was getting sick of having to add this addon every time I open firefox or manually add the sci-hub URL to articles I want to read). It's very easy to get a signed XPI without publishing on AMO and it's approved in seconds, though I haven't looked into autoupdating. It wouldn't take more than a few seconds to do this yourself and link one on the GitHub releases if your AMO account wasn't suspended with the takedown. If you'd like, I can post the one I signed.

**Comment by RoiArthurB** [comment]
If you have one ready I'd love to use it. I'm very busy currently so it will take time before I can take a look at all of this.
Thanks a lot for all your help ! :D

**Comment by Clef-0** [comment]
Alrighty, here's a link. :) https://mega.nz/file/hEo1hArD#X5DbJCdNAiOL0FFzjqJUXhe0fL7X0AyiyFV6I6dvYTo

edit: and no worries!

**Comment by RoiArthurB** [comment]
Ok, thanks bro here's your release : https://github.com/RoiArthurB/Side-Auto_Sci-Hub/releases/tag/v2.0-1

**Comment by RoiArthurB** [comment]
Auto sign release finished for Firefox and Chrome with commit 7220a9d 😁😁😁
