### ISSUE TITLE
Feature request: Compatibility with Firefox's keyboard shortcuts for addons

### ISSUE THREAD

**Issue by FlorentLM** [RoiArthurB/Side-Auto_Sci-Hub#27]
Could be nice to trigger the action with a keyboard shortcut :)

**Comment by RoiArthurB** [comment]
Hi,
I don't use Firefox's keyboard shortcut (except for opening and closing tabs)... So I'll need your help for this one : What shortcut sounds the best for you to trigger the plugin ? :thinking: :monocle_face:

**Comment by FlorentLM** [comment]
Could be Ctrl + Shift + K or L, it's not used by anything stock I believe
