### ISSUE TITLE
Corrupted SVG makes Chrome install impossible

### ISSUE THREAD

**Issue by RoiArthurB** [RoiArthurB/Side-Auto_Sci-Hub#6]
**Describe the bug**
@Jackymancs4  The SVG is corrupted and Firefox give me some warnings about it and the plugin is impossible to install on chrome because of the SVG file... 

I don't know how it works so can you help me with it? 
The screenshot below is the firefox message (it's not much but it's all what I have) ^^"

**Screenshots**
![image](https://user-images.githubusercontent.com/16764085/65598678-43fc2100-df9c-11e9-9331-16124bbe8615.png)

**Desktop (please complete the following information):**
 - Browser Chrome & Firefox
 - Version 1.3

**Comment by Jackymancs4** [comment]
I'm experiencing the very same problem on Chrome and I was already looking into it.
Firefox on the other side does not complain. Can you show me the steps to get what the screenshot shows?

Besides, if you can wait a couple hours I'll come back with a solution, if not I suggest releasing a 1.3.1 hotfix in which you revert b3613ebdde1f18ab3839abf7f6b5694415ad754b

**Comment by Jackymancs4** [comment]
If you prefer, I can submit you a raster of `logo.svg` in png to use as a filler.

**Comment by RoiArthurB** [comment]
> Besides, if you can wait a couple hours I'll ...

Don't worry, take your time, I'm reverting to the previous version on chrome and leaving it on firefox cause it's still working ^^

> Can you show me the steps to get what the screenshot shows?

It's simply when I'm uploading a plugin on Ff it analyze the code and dislay warnings and errors (as a normal compilator), that's all (nothing more sorry :x )

> If you prefer, I can submit you a raster of `logo.svg` in png to use as a filler.

I know nothing about images on plugins (and not much about plugins neither...) so up to you ^^ You're the designer of the plugin and I'll let you do it as you prefer 😄

**Comment by RoiArthurB** [comment]
Even with just the revert commit it doesn't fix the issue for chrome... So I'll upload back to the v1.1 ^^

Also, I took an eye on the svg code and there's a lot of inkscape code... Couldn't you create a minified export or something without InkS. tags? 🤔

**Comment by Jackymancs4** [comment]
> It's simply when I'm uploading a plugin on Ff it analyze the code and dislay warnings and errors (as a normal compilator), that's all (nothing more sorry :x )

No problem, I was able to replicate the message using https://github.com/mozilla/web-ext and https://github.com/mozilla/addons-linter (the problem arise here https://github.com/mozilla/addons-linter/blob/a5b46c52d125c09324a1cbc36d81f5438c622777/src/parsers/manifestjson.js#L511)

The apparent corruption is indeed caused by the odd xhtml notation used by the last version of inkscape (never been a problem before). It is fixable.

Unluckily, due to this outstanding bug (https://bugs.chromium.org/p/chromium/issues/detail?id=29683) SVG icons are not an option at all for Chrome.

It is my fault, I should have checked before. All my works on web extensions are always been on the Firefox platform, so today I learned something.

**Comment by Jackymancs4** [comment]
If you still like my design, I will replace all svg with png files, exported on the right resolution. Still, I'm sorry for wasting your time 😅

**Comment by RoiArthurB** [comment]
> It is my fault, I should have checked before. All my works on web extensions are always been on the Firefox platform, so today I learned something.

It's okay, don't worry ^^ The best point is that you learned something ^^

> If you still like my design

Of course I love Squircled icons 😍 

> sorry for wasting your time 

You don't I learned some things with all your links ! It was a pleasure to received your help ^^
